baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Alex Asemota'
theme = 'jughead'

[module]
replacements = "github.com/ananthb/jughead -> ../.."
[module.hugoVersion]
min = "0.120.0" 
extended = true
[[module.imports]]
path = "github.com/ananthb/jughead"

[[menu.main]]
name = "Resume"
url = "/resume"
weight = 1

[[menu.main]]
name = "Blog"
url = "/blog"
weight = 1

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]
[params]
  math = true
