baseURL = 'https://alexasemota.netlify.app/'
languageCode = 'en-us'
title = 'Alex Asemota'
theme = 'jughead'

[[menu.main]]
name = "Resume"
url = "/resume"
weight = 1

[[menu.main]]
name = "Blog"
url = "/blog"
weight = 1

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]
[params]
  math = true
