baseURL = 'https://alexasemota.netlify.app'
languageCode = 'en-us'
title = 'Alex Asemota'
theme = 'jughead'

[params]
subtitle = "Portfolio and blog theme for Hugo."
description = "Demo site for Jughead, a portfolio and blog theme for Hugo."
colourScheme = "blue"
mainSections = ["blog", "links"]
math = true

[[menu.main]]
name = "Resume"
url = "/resume"
weight = 1

[[menu.main]]
name = "Blog"
url = "/blog"
weight = 1

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]
  
